<?php
$isEnabled = $block->isModuleEnabled();
if (!$isEnabled) {
    return;
}
$partnerId = $block->getPartnerId();
$jwtToken = $block->getJwtToken();
if (!$jwtToken) {
    return;
}
?>
<script>
    require.config({
        map: {
            '*': {
                'trueloyal': 'https://cdn.trueloyal.com/js/all.js'
            }
        }
    });

    require(['trueloyal'], function () {
        let init_data = {
            "partner_id": "<?= /* @noEscape */ $partnerId ?>",
            "jwt_token": "<?= $block->escapeJs($jwtToken) ?>",
            "version": "v2",
            "server": "https://app.trueloyal.com"
        };
        _zrl.push(['init', init_data]);
    });
</script>
