<?php
$isEnabled = $block->isModuleEnabled();
if (!$isEnabled) {
    return;
}
$partnerId = $block->getPartnerId();
?>
<script>
    require.config({
        map: {
            '*': {
                'zinrelo': 'https://cdn.zinrelo.com/js/all.js'
            }
        }
    });

    require([
            'jquery',
            'zinrelo',
            'jquery/jquery.cookie'
        ],
        function ($, zinrelo,) {
            $(document).ready(function () {
                // Your AJAX request code here
                let url = window.BASE_URL + "loyaltyRewards/loyaltyrewards/index";
                let isRequest = $.cookie('zinrelo');
                if (!isRequest | undefined) {
                    $.ajax({
                        url: url, // Adjust the URL as needed
                        type: 'POST',
                        dataType: 'json',
                        cache: false,
                        success: function (response) {
                            let init_data = {
                                "partner_id": response.partnerId,
                                "jwt_token": response.tokenData,
                                "version": "v2",
                                "server": "https://app.zinrelo.com"
                            };
                            _zrl.push(['init', init_data]);
                        },
                        error: function () {
                            console.error('AJAX request failed.');
                        }
                    });
                } else {
                    let init_data = {
                        "partner_id": "<?= /* @noEscape */ $partnerId ?>",
                        "jwt_token": isRequest,
                        "version": "v2",
                        "server": "https://app.zinrelo.com"
                    };
                    _zrl.push(['init', init_data]);
                }
            });
        });
</script>
