<?php
$zinreloHelper = $this->helper(Zinrelo\LoyaltyRewards\Helper\Config ::class);
$zinreloQuoteItem = $zinreloHelper->getZinreloQuoteItemByItemId($block->getItem()->getId());
if ($zinreloQuoteItem->getIsZinreloFreeProduct()) { ?>
    <?php if ($block->isProductVisibleInSiteVisibility()):?>
    <?php endif ?>
<?php } else {
    ?>
    <a class="action action-edit"
       href="<?= $block->escapeUrl($block->getConfigureUrl()) ?>"
       title="<?= $block->escapeHtmlAttr(__('Edit item parameters')) ?>">
        <span><?= $block->escapeHtml(__('Edit')) ?></span>
    </a>
    <?php
} ?>
