<?php
$trueloyalHelper = $this->helper(TrueLoyal\LoyaltyRewards\Helper\Config ::class);
$trueloyalQuoteItem = $trueloyalHelper->getTrueLoyalQuoteItemByItemId($block->getItem()->getId());
if ($trueloyalQuoteItem->getIsTrueLoyalFreeProduct()) { ?>
    <?php if ($block->isProductVisibleInSiteVisibility()):?>
    <?php endif ?>
<?php } else {
    ?>
    <a class="action action-edit"
       href="<?= $block->escapeUrl($block->getConfigureUrl()) ?>"
       title="<?= $block->escapeHtmlAttr(__('Edit item parameters')) ?>">
        <span><?= $block->escapeHtml(__('Edit')) ?></span>
    </a>
    <?php
} ?>
