<?php
$zinreloHelper = $this->helper('Zinrelo\LoyaltyRewards\Helper\Config');
$zinreloQuoteItem = $zinreloHelper->getZinreloQuoteItemByItemId($block->getItem()->getId());
if ($zinreloQuoteItem->getIsZinreloFreeProduct()) { ?>
<?php } else { ?>
    <a href="#"
       title="<?= $block->escapeHtml(__('Remove item')) ?>"
       class="action action-delete"
       data-post='<?= /* @noEscape */ $block->getDeletePostJson() ?>'>
    <span>
        <?= $block->escapeHtml(__('Remove item')) ?>
    </span>
    </a>
<?php } ?>
