<?php
$trueloyalHelper = $this->helper('TrueLoyal\LoyaltyRewards\Helper\Config');
$trueloyalQuoteItem = $trueloyalHelper->getTrueLoyalQuoteItemByItemId($block->getItem()->getId());
if ($trueloyalQuoteItem->getIsTrueLoyalFreeProduct()) { ?>
<?php } else { ?>
    <a href="#"
       title="<?= $block->escapeHtml(__('Remove item')) ?>"
       class="action action-delete"
       data-post='<?= /* @noEscape */ $block->getDeletePostJson() ?>'>
    <span>
        <?= $block->escapeHtml(__('Remove item')) ?>
    </span>
    </a>
<?php } ?>
