<?php
$quote = $block->helper->getQuote();
$zinreloQuote = $this->helper->getZinreloQuoteByQuoteId($quote->getId());
$redeemReward = $zinreloQuote->getRedeemRewardDiscount();
$rewardData = $block->helper->getRewardRulesData($quote, $redeemReward);
$customerEmail = $block->getCustomerEmail();
$points = $block->getRewardPoints();
$redeemUrl = $block->getFormAction();
$redeemRules = $block->getRedeemRules();
$isEnabled = $block->helper->isRewardDropDownEnable();
if (($isEnabled && !empty($customerEmail) && $points != "error" && !empty($redeemRules)) ||
    ($isEnabled && $zinreloQuote->getRewardRulesData() != "")
) {
    $points = ($points == "error") ? 0 : $points;
    $message = $block->helper->getRewardLabelAtCartPage();
    if (str_contains($message, "{{AVAILABLE_POINTS}}")) {
        $message = str_replace("{{AVAILABLE_POINTS}}", "<strong>$points</strong>", $message);
    } else {
        $message = "<strong>$points</strong> " . $message;
    } ?>
    <div class="reward-point">
        <div class="redeem-label">
            <?= /* @noEscape */
            __(
                $message
            ); ?>
        </div>
        <div class="reward-list">
            <?php if (!$block->canCancelRedeem()) { ?>
                <select class="redeem-reward-selector" name="redeem-reward" id="redeem-reward">
                    <option value=""> <?= /* @noEscape */ __("Select a reward") ?> </option>
                    <?php foreach ($redeemRules as $key => $value) { ?>
                        <pre><?php echo json_encode($value, JSON_PRETTY_PRINT); ?></pre>
                        <option 
                            value="<?= /* @noEscape */ $value["reward_id"]; ?>" 
                            data-rule="<?= /* @noEscape */ $value["rule"]; ?>"
                            data-conversion-rate="<?= /* @noEscape */ $value["conversion_rate"] ?? 0; ?>"
                            data-min-redemption="<?= /* @noEscape */ $value["minimum_redemption_limit"] ?? 0; ?>"
                            data-max-redemption="<?= /* @noEscape */ $value["maximum_redemption_limit"] ?? 0; ?>">
                            <?= /* @noEscape */ __($value["reward_name"]); ?>
                        </option>
                    <?php } ?>
                </select>
                <input type="submit" class="redeem" value="<?= /* @noEscape */ __("Apply"); ?>"
                id="redeem" title="<?= /* @noEscape */ __("Apply reward"); ?>">
            <?php } else { ?>
                <select class="redeem-reward-selector" name="redeem-reward" id="cancel-reward" disabled>
                    <option value="<?= /* @noEscape */ $rewardData["reward_id"] ?>" selected>
                        <?= /* @noEscape */ __($rewardData["reward_name"]); ?>
                    </option>
                </select>
                <input type="submit" class="cancel-redeem" value="<?= /* @noEscape */ __("Cancel"); ?>"
                id="cancel-redeem" title="<?= /* @noEscape */ __("Cancel reward"); ?>">
            <?php } ?>
        </div>
        <div id="modalOverlay"></div>
        <div id="flexiblePointsModal" class="modal-container">
            <div class="modal-header">
                <h2>Redeem Flexible Reward</h2>
                <span class="close-btn">×</span>
            </div>
            <div class="modal-body">
                <p>You have <strong><?= /* @noEscape */ $points; ?></strong> points. <br>
                Enter the number of points you'd like to redeem (minimum <strong id="minRedemption"></strong>, maximum <strong id="maxRedemption"></strong>)</p>
                <input type="number" id="redeemPointsInput" value="" />
                <p class="discount-preview">You will get a discount of <strong id="discountAmount">$0.00</strong>. Maximum discount applicable - <strong id="maxdiscountAmount">$0.00</strong>.</p>
            </div>
            <div class="modal-footer">
                <button class="apply-btn">Apply</button>
                <button class="cancel-btn">Cancel</button>
            </div>
        </div>
    </div>

    <script>
        require([
            'jquery',
            'Magento_Checkout/js/model/shipping-rate-service',
            'jquery/ui',
            'mage/cookies'
        ], function ($, shippingrateservice) {
            <?php if (empty($rewardData)) : ?>
                if ($.mage.cookies.get('zinrelo_shipping_selected')) {
                    $.mage.cookies.clear('zinrelo_shipping_selected');
                }
            <?php endif; ?>

            function applyFlexiReward() {
                var redeemRewardSelector = $(".redeem-reward-selector").val();
                var inputPoints = parseInt($("#redeemPointsInput").val(), 10) || 0;

                $(".redeem-reward-selector").css("border-color", "#726d6d");
                $("#redeem-reward").prop('disabled', true);
                $("#redeem").prop('disabled', true);
                $('body').trigger('processStart');
                $.ajax({
                    url: '<?= /* @noEscape */ $redeemUrl ?>',
                    dataType: 'json',
                    type: 'POST',
                    data: {
                        redeem_reward: redeemRewardSelector,
                        redeem_points: inputPoints
                    },
                    success: function (data) {
                        window.location.reload();
                    }
                });
            }

            function closeFlexiModal() {
                $("#modalOverlay").hide();
                $("#flexiblePointsModal").hide();
                $("body").removeClass("no-scroll");

                // Reset dropdown to default "Select a reward"
                const rewardSelector = $(".redeem-reward-selector");
                rewardSelector.val(""); // Reset selected value
                rewardSelector.css("border-color", "#726d6d"); // Reset any border color styles
            }

            $('#redeem').click(function (event) {
                var redeemRewardSelector = jQuery(".redeem-reward-selector").val();
                var selectedOption = $("#redeem-reward option:selected");
                var rule = selectedOption.data("rule");
                if (rule === "flexible_points_reward") {
                    var minRedemption = parseInt(selectedOption.data("min-redemption")) || 0;
                    var maxRedemption = parseInt(selectedOption.data("max-redemption")) || 0;
                    event.preventDefault();
                    var defaultPoints = <?= (int) $points ?>;
                    var conversionRate = parseFloat(selectedOption.data("conversionRate")) || 0;
                    var cartTotal = window.checkoutConfig.totalsData.subtotal;
                    defaultPoints = Math.min(cartTotal*conversionRate, Math.max(minRedemption, Math.min(defaultPoints, maxRedemption)));
                    $("#redeemPointsInput")
                        .attr("min", minRedemption)
                        .attr("max", maxRedemption)
                        .val(defaultPoints);
                    var discount = (defaultPoints / conversionRate).toFixed(2);
                    $("#discountAmount").text(`$${discount}`);
                    $("#maxdiscountAmount").text(`$${discount}`);
                    $("#minRedemption").text(`${minRedemption}`);
                    $("#maxRedemption").text(`${maxRedemption}`);
                    $("#modalOverlay").show();
                    $("#flexiblePointsModal").show();
                    $("body").addClass("no-scroll");
                    return;
                }
                if (redeemRewardSelector != "") {
                    $(".redeem-reward-selector").css("border-color", "#726d6d");
                    $("#redeem-reward").prop('disabled', true);
                    $("#redeem").prop('disabled', true);
                    jQuery('body').trigger('processStart');
                    jQuery.ajax({
                        url: '<?= /* @noEscape */ $redeemUrl ?>',
                        dataType: 'json',
                        data: {'redeem_reward': redeemRewardSelector},
                        type: 'post',
                        global:false,
                        showLoader: false,
                        success: function (data) {
                            let result = data;
                            window.location.reload();
                        }
                    });
                } else {
                    $(".redeem-reward-selector").css("border-color", "red");
                }
            });
            $(".apply-btn").click(function () {
                applyFlexiReward();
            });
            $(".cancel-btn, .close-btn").click(function () {
                closeFlexiModal();
            });
            $('#cancel-redeem').click(function () {
                $('#cancel-redeem').attr('disabled', true);
                jQuery('body').trigger('processStart');
                jQuery.ajax({
                    url: '<?= /* @noEscape */ $redeemUrl ?>',
                    dataType: 'json',
                    data: {'redeem_reward': 'cancel'},
                    type: 'post',
                    global:false,
                    showLoader: false,
                    success: function (data) {
                        let result = data;
                        window.location.reload();
                    }
                });
            });
            $("#redeemPointsInput").on("input", function () {
                var selectedOption = $("#redeem-reward option:selected");

                var conversionRate = parseFloat(selectedOption.data("conversion-rate")) || 0;
                var minRedemption = parseInt(selectedOption.data("min-redemption")) || 0;
                var maxRedemption = parseInt(selectedOption.data("max-redemption")) || 0;

                var inputPoints = parseInt($(this).val(), 10) || 0;
                if (inputPoints < minRedemption) {
                    discountPoints = 0;
                } else {
                    var cartTotal = window.checkoutConfig.totalsData.subtotal;
                    discountPoints = Math.min(cartTotal*conversionRate, Math.max(minRedemption, Math.min(inputPoints, maxRedemption)));
                }
                var discount = (discountPoints / conversionRate).toFixed(2);
                $("#discountAmount").text(`$${discount}`);
            });
        });
    </script>
    <?php
} ?>
